modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "https://kubejs.com/support?source=kubejs_mekanism&mc=1902&loader=forge"
license = "GNU LGPLv3"

[[mods]]
modId = "kubejs_mekanism"
version = "${version}"
displayName = "KubeJS Mekanism"
authors = "LatvianModder"
description = '''
KubeJS Mekanism integration
'''
license = "GNU LGPLv3"

[[dependencies.kubejs_mekanism]]
modId = "kubejs"
mandatory = true
versionRange = "[2001.6.4-build.121,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.kubejs_mekanism]]
modId = "mekanism"
mandatory = true
versionRange = "[10.4.5,)"
ordering = "AFTER"
side = "BOTH"